// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.jin.proto;

public interface StudentInfoRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:StudentInfoRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>int32 age = 2;</code>
   */
  int getAge();
}
