// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.jin.proto;

public interface StudentInfoResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.jin.proto.StudentInfoResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string status = 1;</code>
   */
  java.lang.String getStatus();
  /**
   * <code>string status = 1;</code>
   */
  com.google.protobuf.ByteString
      getStatusBytes();
}
