// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.jin.proto;

public final class Student {
  private Student() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_jin_proto_MyRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_jin_proto_MyRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_jin_proto_MyResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_jin_proto_MyResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_jin_proto_StudentRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_jin_proto_StudentRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_jin_proto_StudentResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_jin_proto_StudentResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_jin_proto_StudentInfoRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_jin_proto_StudentInfoRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_jin_proto_StudentInfoResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_jin_proto_StudentInfoResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_jin_proto_StreamRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_jin_proto_StreamRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_jin_proto_StreamResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_jin_proto_StreamResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rStudent.proto\022\rcom.jin.proto\"\035\n\tMyRequ" +
      "est\022\020\n\010username\030\001 \001(\t\"\036\n\nMyResponse\022\020\n\010r" +
      "ealname\030\001 \001(\t\"\035\n\016StudentRequest\022\013\n\003age\030\001" +
      " \001(\005\":\n\017StudentResponse\022\014\n\004name\030\001 \001(\t\022\013\n" +
      "\003age\030\002 \001(\005\022\014\n\004city\030\003 \001(\t\"/\n\022StudentInfoR" +
      "equest\022\014\n\004name\030\001 \001(\t\022\013\n\003age\030\002 \001(\005\"%\n\023Stu" +
      "dentInfoResponse\022\016\n\006status\030\001 \001(\t\"%\n\rStre" +
      "amRequest\022\024\n\014request_info\030\001 \001(\t\"\'\n\016Strea" +
      "mResponse\022\025\n\rresponse_info\030\001 \001(\t2\336\002\n\016Stu" +
      "dentService\022M\n\024GetStudentByUsername\022\030.co",
      "m.jin.proto.MyRequest\032\031.com.jin.proto.My" +
      "Response\"\000\022U\n\020getStudentsByAge\022\035.com.jin" +
      ".proto.StudentRequest\032\036.com.jin.proto.St" +
      "udentResponse\"\0000\001\022Y\n\014saveStudents\022!.com." +
      "jin.proto.StudentInfoRequest\032\".com.jin.p" +
      "roto.StudentInfoResponse\"\000(\001\022K\n\006BiTalk\022\034" +
      ".com.jin.proto.StreamRequest\032\035.com.jin.p" +
      "roto.StreamResponse\"\000(\0010\001B\032\n\rcom.jin.pro" +
      "toB\007StudentP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_jin_proto_MyRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_jin_proto_MyRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_jin_proto_MyRequest_descriptor,
        new java.lang.String[] { "Username", });
    internal_static_com_jin_proto_MyResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_jin_proto_MyResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_jin_proto_MyResponse_descriptor,
        new java.lang.String[] { "Realname", });
    internal_static_com_jin_proto_StudentRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_jin_proto_StudentRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_jin_proto_StudentRequest_descriptor,
        new java.lang.String[] { "Age", });
    internal_static_com_jin_proto_StudentResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_jin_proto_StudentResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_jin_proto_StudentResponse_descriptor,
        new java.lang.String[] { "Name", "Age", "City", });
    internal_static_com_jin_proto_StudentInfoRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_com_jin_proto_StudentInfoRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_jin_proto_StudentInfoRequest_descriptor,
        new java.lang.String[] { "Name", "Age", });
    internal_static_com_jin_proto_StudentInfoResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_com_jin_proto_StudentInfoResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_jin_proto_StudentInfoResponse_descriptor,
        new java.lang.String[] { "Status", });
    internal_static_com_jin_proto_StreamRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_com_jin_proto_StreamRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_jin_proto_StreamRequest_descriptor,
        new java.lang.String[] { "RequestInfo", });
    internal_static_com_jin_proto_StreamResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_com_jin_proto_StreamResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_jin_proto_StreamResponse_descriptor,
        new java.lang.String[] { "ResponseInfo", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
